### PR TITLE
Check if GLOBAL_TAG_TYPES is already defined

### PR DESCRIPTION
**Pull request by ghost**
When using YSI (cloned from the repo, not the release page) it shows a warning that GLOBAL_TAG_TYPES is already defined.
Hence checking if it was already defined.

### CODE REVIEW

**Comment by Y-Less** [comment]
I left that warning there on purpose.  They are the same:

https://github.com/Y-Less/indirection/blob/27d88aed1bfc260445899c708bc1f0555ab763f3/indirection.inc#L81-L85
https://github.com/pawn-lang/YSI-Includes/blob/7adbca0a275834a6693148c18baad11c528ce535/YSI_Core/y_core/y_globaltags.inc#L84-L88

The only reason you would still be getting that warning is you don't have the latest version of one or the other.

**Comment by ghost** [comment]
Hmm.. when downloading the YSI library from the releases page it does not occur. When using the cloned repository (which I did for that `entry` issue), it does.
Just looked, and YSI repository currently includes https://github.com/Y-Less/indirection/tree/b7535854e68f8e25578ef96002e4cf536590d1b9 and not the latest https://github.com/Y-Less/indirection/commit/27d88aed1bfc260445899c708bc1f0555ab763f3 -That does indeed fix this tiny "issue".

**Comment by Y-Less** [comment]
Why are you not using sampctl?

**Comment by Vince0789** [comment]
The thing is, it does occur with sampctl. Specifically installing `YSI-Coding/y_hooks` on its own triggers this warning.

**Comment by ghost** [comment]
That is a very good question. Been inactive for several years (when sampctl became a thing evidently), started helping a server when I came back and have been there ever since.
JustMichael did come up with sampctl once and started setting things up but there were some issues and those never got fixed. (Besides, compiling that gamemode on GNU/Linux causes issues with FCNPC, which I still haven't figured out). Never was in situations where sampctl would be pretty much required as appearantly now. Will definitely start looking into/using it soon.

**Comment by Y-Less** [comment]
> 
> 
> The thing is, it does occur with sampctl. Specifically installing `YSI-Coding/y_hooks` on its own triggers this warning.

Yeah, that repo is well out of date.  YSI-Includes is the canonical repo, and entirely relies on sampctl now.  I used to not use dependencies on YSI because it caused major issues like this.  Then sampctl solved those issues so I started adding dependencies.  Even submodules are useless.

**Pull request closed without merging**
